//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessories2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accessories2()
        {
            this.OutfitIDs = new HashSet<OutfitID>();
        }
    
        public int Accessory2ID { get; set; }
        public string Accessory2Name { get; set; }
        public string Accessory2Photo { get; set; }
        public Nullable<int> Accessory2TypeID { get; set; }
        public Nullable<int> Accessory2ColorID { get; set; }
        public Nullable<int> Accessory2SeasonID { get; set; }
        public Nullable<int> Accessory2OccassionID { get; set; }
    
        public virtual Accessory2Colors Accessory2Colors { get; set; }
        public virtual Accessory2Occassions Accessory2Occassions { get; set; }
        public virtual Accessory2Seasons Accessory2Seasons { get; set; }
        public virtual Accessory2Types Accessory2Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutfitID> OutfitIDs { get; set; }
    }
}
