//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessories5
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accessories5()
        {
            this.OutfitIDs = new HashSet<OutfitID>();
        }
    
        public int Accessory5ID { get; set; }
        public string Accessory5Name { get; set; }
        public string Accessory5Photo { get; set; }
        public Nullable<int> Accessory5TypeID { get; set; }
        public Nullable<int> Accessory5ColorID { get; set; }
        public Nullable<int> Accessory5SeasonID { get; set; }
        public Nullable<int> Accessory5OccassionID { get; set; }
    
        public virtual Accessory5Colors Accessory5Colors { get; set; }
        public virtual Accessory5Occassions Accessory5Occassions { get; set; }
        public virtual Accessory5Seasons Accessory5Seasons { get; set; }
        public virtual Accessory5Types Accessory5Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutfitID> OutfitIDs { get; set; }
    }
}
