//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accessory()
        {
            this.OutfitIDs = new HashSet<OutfitID>();
        }
    
        public int AccessoryID { get; set; }
        public string AccessoryName { get; set; }
        public string AccessoryPhoto { get; set; }
        public int AccessoryTypeID { get; set; }
        public int AccessoryColorID { get; set; }
        public int AccessorySeasonID { get; set; }
        public int AccessoryOccassionID { get; set; }
    
        public virtual AccessoryColor AccessoryColor { get; set; }
        public virtual AccessoryOccasion AccessoryOccasion { get; set; }
        public virtual AccessorySeason AccessorySeason { get; set; }
        public virtual AccessoryType AccessoryType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutfitID> OutfitIDs { get; set; }
    }
}
