//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessories4
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accessories4()
        {
            this.OutfitIDs = new HashSet<OutfitID>();
        }
    
        public int Accessory4ID { get; set; }
        public string Accessory4Name { get; set; }
        public string Accessory4Photo { get; set; }
        public Nullable<int> Accessory4TypeID { get; set; }
        public Nullable<int> Accessory4ColorID { get; set; }
        public Nullable<int> Accessory4SeasonID { get; set; }
        public Nullable<int> Accessory4OccassionID { get; set; }
    
        public virtual Accessory4Colors Accessory4Colors { get; set; }
        public virtual Accessory4Occassions Accessory4Occassions { get; set; }
        public virtual Accessory4Seasons Accessory4Seasons { get; set; }
        public virtual Accessory4Types Accessory4Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutfitID> OutfitIDs { get; set; }
    }
}
