//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bottom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bottom()
        {
            this.OutfitIDs = new HashSet<OutfitID>();
        }
    
        public int BottomID { get; set; }
        public string BottomName { get; set; }
        public string BottomPhoto { get; set; }
        public int BottomTypeID { get; set; }
        public int BottomColorID { get; set; }
        public int BottomSeasonID { get; set; }
        public int BottomOccasionID { get; set; }
    
        public virtual BottomsColor BottomsColor { get; set; }
        public virtual BottomsOccasion BottomsOccasion { get; set; }
        public virtual BottomsSeason BottomsSeason { get; set; }
        public virtual BottomsType BottomsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutfitID> OutfitIDs { get; set; }
    }
}
