//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WardrobeMVCEntities : DbContext
    {
        public WardrobeMVCEntities()
            : base("name=WardrobeMVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accessory> Accessories { get; set; }
        public virtual DbSet<Accessories2> Accessories2 { get; set; }
        public virtual DbSet<Accessories3> Accessories3 { get; set; }
        public virtual DbSet<Accessories4> Accessories4 { get; set; }
        public virtual DbSet<Accessories5> Accessories5 { get; set; }
        public virtual DbSet<Accessory2Colors> Accessory2Colors { get; set; }
        public virtual DbSet<Accessory2Occassions> Accessory2Occassions { get; set; }
        public virtual DbSet<Accessory2Seasons> Accessory2Seasons { get; set; }
        public virtual DbSet<Accessory2Types> Accessory2Types { get; set; }
        public virtual DbSet<Accessory3Colors> Accessory3Colors { get; set; }
        public virtual DbSet<Accessory3Occassions> Accessory3Occassions { get; set; }
        public virtual DbSet<Accessory3Seasons> Accessory3Seasons { get; set; }
        public virtual DbSet<Accessory3Types> Accessory3Types { get; set; }
        public virtual DbSet<Accessory4Colors> Accessory4Colors { get; set; }
        public virtual DbSet<Accessory4Occassions> Accessory4Occassions { get; set; }
        public virtual DbSet<Accessory4Seasons> Accessory4Seasons { get; set; }
        public virtual DbSet<Accessory4Types> Accessory4Types { get; set; }
        public virtual DbSet<Accessory5Colors> Accessory5Colors { get; set; }
        public virtual DbSet<Accessory5Occassions> Accessory5Occassions { get; set; }
        public virtual DbSet<Accessory5Seasons> Accessory5Seasons { get; set; }
        public virtual DbSet<Accessory5Types> Accessory5Types { get; set; }
        public virtual DbSet<AccessoryColor> AccessoryColors { get; set; }
        public virtual DbSet<AccessoryOccasion> AccessoryOccasions { get; set; }
        public virtual DbSet<AccessorySeason> AccessorySeasons { get; set; }
        public virtual DbSet<AccessoryType> AccessoryTypes { get; set; }
        public virtual DbSet<Bottom> Bottoms { get; set; }
        public virtual DbSet<BottomsColor> BottomsColors { get; set; }
        public virtual DbSet<BottomsOccasion> BottomsOccasions { get; set; }
        public virtual DbSet<BottomsSeason> BottomsSeasons { get; set; }
        public virtual DbSet<BottomsType> BottomsTypes { get; set; }
        public virtual DbSet<Outerwear> Outerwears { get; set; }
        public virtual DbSet<OuterwearColor> OuterwearColors { get; set; }
        public virtual DbSet<OuterwearOccassion> OuterwearOccassions { get; set; }
        public virtual DbSet<OuterwearSeason> OuterwearSeasons { get; set; }
        public virtual DbSet<OuterwearType> OuterwearTypes { get; set; }
        public virtual DbSet<OutfitID> OutfitIDs { get; set; }
        public virtual DbSet<SecondLayerTopColor> SecondLayerTopColors { get; set; }
        public virtual DbSet<SecondLayerTopOccasion> SecondLayerTopOccasions { get; set; }
        public virtual DbSet<SecondLayerTop> SecondLayerTops { get; set; }
        public virtual DbSet<SecondLayerTopSeason> SecondLayerTopSeasons { get; set; }
        public virtual DbSet<SecondLayerTopType> SecondLayerTopTypes { get; set; }
        public virtual DbSet<ShoeColor> ShoeColors { get; set; }
        public virtual DbSet<ShoeOccasion> ShoeOccasions { get; set; }
        public virtual DbSet<Sho> Shoes { get; set; }
        public virtual DbSet<ShoeSeason> ShoeSeasons { get; set; }
        public virtual DbSet<ShoeType> ShoeTypes { get; set; }
        public virtual DbSet<Top> Tops { get; set; }
        public virtual DbSet<TopColor> TopColors { get; set; }
        public virtual DbSet<TopOccassion> TopOccassions { get; set; }
        public virtual DbSet<TopSeason> TopSeasons { get; set; }
        public virtual DbSet<TopType> TopTypes { get; set; }
    }
}
