//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outerwear
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Outerwear()
        {
            this.OutfitIDs = new HashSet<OutfitID>();
        }
    
        public int OuterwearID { get; set; }
        public string OuterwearName { get; set; }
        public string OuterwearPhoto { get; set; }
        public Nullable<int> OuterwearTypeID { get; set; }
        public Nullable<int> OuterwearColorID { get; set; }
        public Nullable<int> OuterwearSeasonID { get; set; }
        public Nullable<int> OuterwearOccassionID { get; set; }
    
        public virtual OuterwearColor OuterwearColor { get; set; }
        public virtual OuterwearOccassion OuterwearOccassion { get; set; }
        public virtual OuterwearSeason OuterwearSeason { get; set; }
        public virtual OuterwearType OuterwearType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutfitID> OutfitIDs { get; set; }
    }
}
