//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecondLayerTop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SecondLayerTop()
        {
            this.OutfitIDs = new HashSet<OutfitID>();
        }
    
        public int SecondLayerTopID { get; set; }
        public string SecondLayerTopName { get; set; }
        public string SecondLayerTopPhoto { get; set; }
        public Nullable<int> SecondLayerTopTypeID { get; set; }
        public Nullable<int> SecondLayerTopColorID { get; set; }
        public Nullable<int> SecondLayerTopSeasonID { get; set; }
        public Nullable<int> SecondLayerTopOccassionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutfitID> OutfitIDs { get; set; }
        public virtual SecondLayerTopColor SecondLayerTopColor { get; set; }
        public virtual SecondLayerTopOccasion SecondLayerTopOccasion { get; set; }
        public virtual SecondLayerTopSeason SecondLayerTopSeason { get; set; }
        public virtual SecondLayerTopType SecondLayerTopType { get; set; }
    }
}
