//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sho()
        {
            this.OutfitIDs = new HashSet<OutfitID>();
        }
    
        public int ShoesID { get; set; }
        public string ShoeName { get; set; }
        public string ShoePhoto { get; set; }
        public int ShoeTypeID { get; set; }
        public int ShoeColorID { get; set; }
        public int ShoeSeasonID { get; set; }
        public int ShoeOccassionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutfitID> OutfitIDs { get; set; }
        public virtual ShoeColor ShoeColor { get; set; }
        public virtual ShoeOccasion ShoeOccasion { get; set; }
        public virtual ShoeSeason ShoeSeason { get; set; }
        public virtual ShoeType ShoeType { get; set; }
    }
}
